### ISSUE TITLE
A tab can't display more than 8 images

### ISSUE THREAD

**Issue by r03ert0** [ConnectProject/mavoix-app#22]
observed: using the panel I added 11 images, only the first 8 are displayed in the app
expected: all images should be displayed, using horizontal scrolling if necessary (i seem to remember this was the case in the version coded by @Pierre-Green)

**Comment by r03ert0** [comment]
I made the images smaller, so now the limit is >8, but that's not a solution. We need to bring the horizontal scrolling back :)

**Comment by morvanr** [comment]
Yes, I thought it was working fine, I will check what happened here :) Should be an easy one anyway !

**Comment by morvanr** [comment]
@r03ert0 I couldn't reproduce it, horizontal scrolling works fine on my test, let's check this together tomorrow

**Comment by r03ert0** [comment]
maybe it's because I'm testing using the ipad emulator in chrome, and not a real tablet... let's check tomorrow : )

**Comment by morvanr** [comment]
I am also working mostly on a chrome tab because it is practical for the refresh but it is working fine ! let check tomorrow ;)

**Comment by r03ert0** [comment]
fixed
