### ISSUE TITLE
prevent images from flowing when one is moved to the voice bar

### ISSUE THREAD

**Issue by r03ert0** [ConnectProject/mavoix-app#26]
observed: when an image is moved from a tab into the voice bar, the remaining images in the tab flow to occupy the empty space. The position of images becomes then more difficult to learn.

expected: the space left by an image shouldn't be occupied: it should remain empty.

<img width="857" alt="Screenshot 2021-01-01 at 13 29 13" src="https://user-images.githubusercontent.com/2310732/103438680-96af9880-4c35-11eb-92d0-e6686c8f750c.png">

**Comment by morvanr** [comment]
I know how we can do this, but there is a bit of work because it suppose to keep track of the place where an image was and to put it back to the right place when it is remove :)

**Comment by r03ert0** [comment]
maybe the image can be replaced by a transparent placeholder? that would prevent the other images from flowing, and a data- attribute could be used to keep track of the image the placeholder represents...

**Comment by morvanr** [comment]
Already fixed anyway ;) (the new behaviour was in fact much easier to implement that the old one was)

**Comment by r03ert0** [comment]
the images leave nicely their empty space behind, however, they don't come back to their original position after clicking "x" in the voice bar. Here's some screenshots:

1. original config
<img width="518" alt="Screenshot 2020-12-31 at 20 36 38" src="https://user-images.githubusercontent.com/2310732/103423704-666de880-4ba8-11eb-805d-c2d8fef0057c.png">

2. two images moved to the voice bar (also: note the bug in the image size)
<img width="519" alt="Screenshot 2020-12-31 at 20 36 57" src="https://user-images.githubusercontent.com/2310732/103423712-738ad780-4ba8-11eb-8f87-b5407c48139c.png">

3. click "x" in the voice bar: the moved images don't come back to their original config, and the images that were not moved also change their position. It seems that the empty space holder is now using the whole column.
<img width="519" alt="Screenshot 2020-12-31 at 20 37 15" src="https://user-images.githubusercontent.com/2310732/103423733-88676b00-4ba8-11eb-912f-82a25f40b212.png">

**Comment by ntraut** [comment]
Also as the images are still there but transparent we still can drag them from the top panel even if they are in the lower panel.
Not a big issue but maybe we could make the transparent images not draggable like when they are set to be "indisponible"?

**Comment by r03ert0** [comment]
yes, it shouldn't be possible to move the empty space

**Comment by r03ert0** [comment]
fixed
