### ISSUE TITLE
"Invisible" is not respected

### ISSUE THREAD

**Issue by r03ert0** [ConnectProject/mavoix-app#30]
observed: I set an image to "invisible" in mavoix-panel, save, but it still shows up in mavoix-app.
expected: "invisible" images should not appear in mavoix-app.

version git-pulled 31 dec 2020 at 20h30

**Comment by ntraut** [comment]
For me it is working in current master but broken in current debug-romain branch.
Are you sure you didn't forget to save in panel?

**Comment by r03ert0** [comment]
it's working now. I'll close the issue.

**Comment by ntraut** [comment]
Debug-romain branch has still not been fixed so we should make sure it's fixed in that branch before it is merged.

**Comment by r03ert0** [comment]
ok. We should try to merge @morvanr's branch as soon as possible, otherwise we may drift apart too much and the merge will be a mess...

**Comment by ntraut** [comment]
ok, but for the moment there are not any conflict. It's not a merge problem, it's just an introduced bug.

**Comment by r03ert0** [comment]
fixed
