### ISSUE TITLE
App should auto-log-in if there hasn't been a disconnection

### ISSUE THREAD

**Issue by r03ert0** [ConnectProject/mavoix-app#33]
observed: the app asks for logging in every time it's launched, even after just having logged in the previous time. This is very inconvenient when the app is used by people with intellectual disability who can't write the login and password.

expected: the app should remain logged in until a disconnect is performed (there's no way of disconnecting the app at the moment: see issue #15)

**Comment by morvanr** [comment]
pushed on debug-romain, to be tested

**Comment by ntraut** [comment]
To be clearer it only happens after the app has been closed, it doesn't happen when the app remains in background.
