### ISSUE TITLE
Horizontal sliding in one tab breaks display in the others

### ISSUE THREAD

**Issue by r03ert0** [ConnectProject/mavoix-app#36]
observed: I slide horizontally in a tab full of images, then switch to another tab: the tab is displaced to the left and the left-most images invisible.
expected: Sliding on one tab should not affect the display of the other tabs.

<img width="539" alt="Screenshot 2021-01-14 at 10 40 43" src="https://user-images.githubusercontent.com/2310732/104573307-07eb4480-5655-11eb-8817-a5261068dc4b.png">

**Comment by morvanr** [comment]
Fixed

**Comment by r03ert0** [comment]
ah!! this one's fixed in your branch?

**Comment by morvanr** [comment]
Yup work like a charm :)
